server:
  port: 8050

---
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver
